### ISSUE TITLE
Support private registries such as ACR

### ISSUE THREAD

**Issue by agolomoodysaada** [replicatedhq/outdated#13]
Doesn't work with private registries such as Azure Container Registry.
It just says `Unable to get image data`

**Comment by marccampbell** [comment]
@agolomoodysaada when you receive this, is your local docker client logged in to the ACR account that has access to the image?

**Comment by agolomoodysaada** [comment]
Yes. The docker client is logged in. I can pull and push images without any issues.
However, I know that ACR is a non-standard implementation of the docker registry API. So it could be an ACR specific issue; as opposed to a private registry issue.
