### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by arminc** [replicatedhq/outdated#18]
I started a project last year to track versions and vulnerabilities in Kubernetes: https://github.com/arminc/k8s-platform-lcm

I came across your project and I see a lot of similarities. Maybe in the future, we could collaborate.

**Comment by marccampbell** [comment]
@arminc lcm looks great. You are tackling a broader problem than Outdated is. We are looking only to tell if an image has newer tags, but lcm looks to be training to be a dashboard to know the overall health of your images by integrating into Clair and other utilities.  

It would be great to collaborate. If you wanted, you could try vendoring our version detection code here: https://github.com/arminc/k8s-platform-lcm/blob/1d923fb1704fc380392ba4e378cfe9e111a43a9e/internal/versioning/versioning.go#L51

Outdated does a lot more than semver version sorting. This project handles non-semver tags by getting the date of the image, if the image is not running a semver tag. I'd be happy to make a PR here, if you'd be open to it.
