### ISSUE TITLE
Doesn't work on GKE clusters

### ISSUE THREAD

**Issue by ahmetb** [replicatedhq/outdated#4]
> failed to create clientset: No Auth Provider found for name "gcp"

You need to do 

```
import _ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
```

Ditto for others in https://godoc.org/k8s.io/client-go/plugin/pkg/client/auth.

(context: I was testing this for https://github.com/kubernetes-sigs/krew-index/pull/194).

**Comment by divolgin** [comment]
@ahmetb thanks for the report and the code.   this has been resolved.
