### ISSUE TITLE
Doesnt work with multiple contexts

### ISSUE THREAD

**Issue by ryan-dyer** [replicatedhq/outdated#8]
I use a ~/.kube directory which contains a different file for each cluster we manage as well as a separate file for my user.  I export KUBECONFIG containing all of these files.

When my current context is set to clusterA and I attempt to run outdated, it scans and then returns a failure indicating it could not contact clusterB (which it cant given each cluster requires a different VPN connection to access).

IMO, outdated should only operate on the current context.  I notice in the --help there is a kubeconfig override option... why?  I can appreciate a context option here, but kubeconfig?

**Comment by marccampbell** [comment]
@ryan-dyer thanks for the issue. We've updated the plugin to support all of the kubectl flags and the new version is available in the krewindex now. If you update, it should work.
